# Generated by Django 2.2.4 on 2019-10-12 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('codigo_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=25)),
                ('email_empleado', models.EmailField(max_length=25)),
                ('fecha_empleado', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('codigo_inventario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_inventario', models.CharField(max_length=25)),
                ('marca_invetario', models.CharField(max_length=25)),
                ('existencia_inventario', models.IntegerField()),
                ('precio_inventario', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('codigo_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('total_venta', models.FloatField()),
                ('codigo_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion1.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='detallefactura',
            fields=[
                ('codigo_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_producto', models.IntegerField()),
                ('Precio_unitario', models.FloatField()),
                ('precio_total', models.FloatField()),
                ('fecha_detalle', models.DateField()),
                ('codigo_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion1.inventario')),
                ('codigo_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion1.venta')),
            ],
        ),
    ]
